# External Ansible roles required by this repository

- name: ome.basedeps
  src: https://github.com/pwalczysko/ansible-role-basedeps/
  version: fix-repo-rhel

- name: ome.postgresql

- name: ome.omero_server
  version: 5.0.0