---
name: Build

on: 
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: ./test.sh
  upload:
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    env:
      name: omero-server
    steps:
      - name: Get prefix
        id: getprefix
        run: |
          if [ ! -z ${{ env.name }} ]; then
            echo "::set-output name=prefix::${{ github.actor }}/${{ env.name }}:"
          else
            echo "::set-output name=prefix::${{ github.repository }}:"
          fi
      - name: Get tags
        id: gettags
        run: |
          RE='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9-]*\)\([0-9A-Za-z-]*\)'
          base=${GITHUB_REF#tags/*/}
          MAJOR=`echo $base | sed -e "s#$RE#\1#"`
          MINOR=`echo $base | sed -e "s#$RE#\2#"`
          PATCH=`echo $base | sed -e "s#$RE#\3#"`
          value="${{ steps.getprefix.outputs.prefix }}latest"
          value="$value,${{ steps.getprefix.outputs.prefix }}$MAJOR"
          value="$value,${{ steps.getprefix.outputs.prefix }}$MAJOR.$MINOR"
          value="$value,${{ steps.getprefix.outputs.prefix }}$MAJOR.$MINOR.$PATCH"
          echo "$value"
          echo "::set-output name=tags::$value"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.gettags.outputs.tags }}
          push: true
